<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ page import="java.util.*" %>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Transaction History</title>
    <link rel="stylesheet" href="${pageContext.request.contextPath}/CssFolder/viewTransaction.css">
</head>
<body>

<div class="table-container">
    <h2>Passbook Statement Log</h2>
    <p>Account Number: <strong>${sessionScope.account_no}</strong></p>

    <table>
        <thead>
            <tr>
                <th>Date & Time</th>
                <th>Type</th>
                <th>Description</th>
                <th>Amount (₹)</th>
            </tr>
        </thead>
        <tbody>
            <% 
                // Extract the parsed list attribute generated by our Servlet processing loop
                List<Map<String, Object>> list = (List<Map<String, Object>>) request.getAttribute("transactions");
                if (list == null || list.isEmpty()) {
            %>
                <tr>
                    <td colspan="4" style="text-align: center; color: #888;">No transaction history found for this account.</td>
                </tr>
            <% 
                } else {
                    for (Map<String, Object> row : list) {
            %>
                <tr>
                    <td><%= row.get("date") %></td>
                    <td class="<%= row.get("type") %>"><%= row.get("type") %></td>
                    <td><%= row.get("description") %></td>
                    <td><strong>₹ <%= String.format("%,.2f", (Double) row.get("amount")) %></strong></td>
                </tr>
            <% 
                    }
                }
            %>
        </tbody>
    </table>

    <a href="${pageContext.request.contextPath}/Dashboard.jsp" class="btn-back">← Back to Dashboard</a>
</div>

</body>
</html>